

version: '3.8'

services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
    depends_on:
      - php
      - mysql

  php:
    image: php:7.4-apache
    container_name: php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql

  node:
    image: node:lts
    container_name: node
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "npm install && npm start"

  react:
    build: ./react
    container_name: react
    ports:
      - '3000:3000'
    volumes:
      - ./react:/app
    depends_on:
      - node

  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    environment:
      NGROK_PORT: 80
    ports:
      - '4040:4040'
    depends_on:
      - nginx

volumes:
  mysql_data:

